### ISSUE TITLE
AE Bridge immediately breaks off after placing it down

### ISSUE THREAD

**Issue by SigmaSnake** [tom5454/LogisticsBridge#1]
https://imgur.com/a/woTJ6b6 - This is my current setup. When I break off the provider pipe and put a bridge pipe there, and then replace the interface with the AE Bridge, the bridge immediately breaks off.

**Comment by tom5454** [comment]
I managed to reproduce the issue.
The new version fixes it, but it crashes with LogisticsPipes version 0.10.2.204 or 0.10.2.205
(because RS485/LogisticsPipes#1369).
