### ISSUE TITLE
Result Pipe Rendering screen

### ISSUE THREAD

**Issue by ProfTechnology** [tom5454/LogisticsBridge#14]
When i try to open the Result Pipe, with the wrench from thermal dynamics, the game crashes. The same when i try to open the Satellite Bus.

[crash-2019-12-15_15.21.55-client.txt](https://github.com/tom5454/LogisticsBridge/files/3965027/crash-2019-12-15_15.21.55-client.txt)

**Comment by tom5454** [comment]
Please update Logistics Bridge, You are using v0.3.1, the newest version is v1.2.5.
