### ISSUE TITLE
Items dropping out from the system

### ISSUE THREAD

**Issue by MattiaBLX** [tom5454/LogisticsBridge#15]
Here's a video of the issue: https://www.youtube.com/watch?v=KJ4-aXzzFsE
I don't know if this is a problem caused by this mod or LogisticsPipes.

**Comment by tom5454** [comment]
Try the latest (1.3.0) version, I can't reproduce the issue.

**Comment by MattiaBLX** [comment]
Ok, I update to 1.3.0 and now everything works correctly. Thank you!
