### ISSUE TITLE
Crash when entering the world

### ISSUE THREAD

**Issue by NelkGames** [tom5454/LogisticsBridge#18]
After I updated the version of Logistic Pipes (version: 0.10.3.25), LogisticsBridge is crashing my save. I managed to break the block before the world closed and the crash stopped, here's the crash-report.
[crash.zip](https://github.com/tom5454/LogisticsBridge/files/4684155/crash.zip)

**Comment by bziemons** [comment]
I am sorry, I renamed and refactored a few LP internals and because we don't have an API, this was broken too. I'll gladly accept any PRs to create a stable API though.

**Comment by NelkGames** [comment]
I'm happy to have warned you about this problem, and good luck with this amazing project :D
