### ISSUE TITLE
Miscalculation of Result

### ISSUE THREAD

**Issue by SigmaSnake** [tom5454/LogisticsBridge#2]
![2019-09-04_04 23 51](https://user-images.githubusercontent.com/54494265/64243009-39ce9180-cecc-11e9-8020-0fe7501e0719.png)
Certain recipes such as Awakened Draconium craft in sets of four, However, when I order 1, it only recognizes that one was ordered, throwing the rest that was crafted from the result pipe onto the ground. If I order more than 1, say 4, it crafts 4 sets. This is my current setup for reference. I have not a clue why the pipe is red by the way. It works fine.

**Comment by tom5454** [comment]
The Result Pipe can't find a place to put your items, so it drops them on the ground.
Put a basic logistics pipe on the AE Bridge, with default route on, so it puts all of the extra items into your AE system.

**Comment by SigmaSnake** [comment]
@tom5454 It should accept all of the items though. None of them should be falling onto the ground, hence the issue. If I request one awakened draconium, it should realize the recipe crafts four, and accept all four back into the system.

**Comment by nico1207** [comment]
I have the same problem in 1.3.7. I have 3 recipes set up: 1 Copper + 4 Redstone = 1 Red Alloy Ingot, 1 Red Alloy Ingot ->2 Red Alloy Wire, 1 Red Alloy Wire -> 4 Fine Red Alloy Wire. When I request 8 Fine Red Alloy Wire, it tried to make 2 Red Alloy Ingots even though only 1 is needed.
![image](https://user-images.githubusercontent.com/7195044/88682873-782bfb00-d0f3-11ea-9830-3ffae39e1bdd.png)

**Comment by nico1207** [comment]
(All recipes are correct, since everything works fine if I request 8 Fine Red Alloy Wire using the LP Request Table.
