### ISSUE TITLE
[1.12.2] Crash upon loading. 

### ISSUE THREAD

**Issue by aking4125** [tom5454/LogisticsBridge#20]
Hi,

I am getting the following crash upon startup. Possibly related to Logistics Pipes updating to version 0.10.3.29 just a few hours ago?
[crash-2020-05-29_13.02.32-client.txt](https://github.com/tom5454/LogisticsBridge/files/4703215/crash-2020-05-29_13.02.32-client.txt)

Using Logistics Pipes 0.10.3.29
Using Logistics Bridge v1.3.2

**Comment by bziemons** [comment]
sorry!

**Comment by JasonKillsUs** [comment]
have the same crash like aking4125

**Comment by Gryffen1971** [comment]
> 
> 
> Hi,
> 
> I am getting the following crash upon startup. Possibly related to Logistics Pipes updating to version 0.10.3.29 just a few hours ago?
> [crash-2020-05-29_13.02.32-client.txt](https://github.com/tom5454/LogisticsBridge/files/4703215/crash-2020-05-29_13.02.32-client.txt)
> 
> Using Logistics Pipes 0.10.3.29
> Using Logistics Bridge v1.3.2



> 
> 
> have the same crash like aking4125


I have received the same crash;

java.lang.IllegalAccessError: no such constructor: com.tom.logisticsbridge.pipe.BridgePipe.<init>(Item)void/newInvokeSpecial

[Crash Log](https://pastebin.com/ET9JDrVi)

Running same latest versions of Forge and Both Mods and Minecraft 1.12.2

**Comment by Gryffen1971** [comment]
@tom5454,
Could you tell me what was causing the problem and when an update will occur.
Because I want to update both Logistics Pipes and Bridges before i upload an Update to my Mod-Packs.

Thanks

**Comment by tom5454** [comment]
Logistics Pipes code changed. Some files in Logistics Pipes was moved with the update, that LogisticsBridge needs, and could not find.
(If you look at: https://github.com/tom5454/LogisticsBridge/commit/81e6e841895bef977a2f800f48463b199c6ccf70
LogisticsModule class file was moved)

**Comment by Gryffen1971** [comment]
thanks
