### ISSUE TITLE
Crafting Manager Buffer Issue

### ISSUE THREAD

**Issue by SlikNinjaZ** [tom5454/LogisticsBridge#29]
Whenever I add a crafting buffer to the crafting manager and attach it to an inventory, it will not always send the entire amount into the machine.

**Comment by Direwolf20-MC** [comment]
HI there, just popping in to say I have the same problem. Example: I want to craft 8 furnaces:

64 cobble goes into the buffer chest. 
8 cobble goes and gets crafted into a furnace.
The remaining cobble sits in the buffer chest and never moves. 

I love the concept of this upgrade, forcing it to craft 1 complete set of items at a time, but unfortunately it doesn't work at the moment. I know 1.12 is pretty old, but is there any chance you could take a peak? :) If not no worries.

**Comment by tom5454** [comment]
Fixed in the latest release.

**Comment by Direwolf20-MC** [comment]
Thank you - just confirmed its working :D
