### ISSUE TITLE
Not able to access items from Request Table stored in RS Disk drive

### ISSUE THREAD

**Issue by Philipp766** [tom5454/LogisticsBridge#32]
I store my items in an small RS system due to space. If I want to access these items over the Request table or the items stored over the Logistic pipes system with the RS Grid they dont show up. I connected both systems with the rs bridge and the bridge Cable. any ideas what to do?

**Comment by Philipp766** [comment]
![2020-08-02_16 36 43](https://user-images.githubusercontent.com/45693638/89125498-38905500-d4df-11ea-9aec-115c3abcb54f.png)
This is the setup I use. the unrouted cabele goes off to external storage

**Comment by tom5454** [comment]
Try to break and replace the RS Bridge.
Also what version of Logistics Pipes, Logistics Bridge and Refined Storage are you using?

**Comment by Philipp766** [comment]
apparently you cannot connect the RS bridge from the bottom. It connects but no logic is happening. I put the RS brige and the LP brige side to side and that works. Thank you for your help

**Comment by Philipp766** [comment]
with that I mean items can go from the LP system to the RS system but they cannot access each other to exchange Items. you can pipe them in tho

**Comment by tom5454** [comment]
Yes the bridge pipe only checks horizontally, I will make it so it wont connect at all.
