### ISSUE TITLE
[Request] Support for Crafting Sign Creator on Crafting Manager

### ISSUE THREAD

**Issue by tjsd** [tom5454/LogisticsBridge#36]
Title says it all, would love if right clicking a crafting manager with the Crafting Sign Creator would put a small label on the pipe with the satellite and result pipe names on it.

**Comment by tom5454** [comment]
I added Crafting Manager signs, you have to right click the sign creator to switch to Crafting Manager sign mode (item.logisticspipes.sign_creator.2.name, name bugged).
