### ISSUE TITLE
Results Pipe wont Pull when Updated

### ISSUE THREAD

**Issue by desagas** [tom5454/LogisticsBridge#37]
I have tested this a few times in 1.3.8, in FTB interactions 2.0.5.

I tried looking through old issues, but could find none.

Here is my current set up:
Advanced Mixer: front face - item sat pipe, top face - fluid sat pipe and crafting manager above, right face - result pipe.

What is happening:
Provided I place the machine first, the mixer in this case, name all the pipes, and set the crafting recipe in the manager, everything works. However, even with no changes to the pipes, if I break the machine and replace it with another machine, even the exact same machine, it stops pulling result items. I have tested this with GT machines, RFTool crafters, ExtraUtils crafters, etc. If the connected machine is removed and then replaced, the recipe result pipe will no longer work. In GT, we constantly update machine tiers, so, this means that with every update, we have to reset our pipes.

The way to solve now:
we have to break and replace the results pipe after replacing the machine it is connected to, and then name it. Then, in crafting manager, we need to unset results pipe, exit, and then set it once again.

Expected performance:
Similar to the satellite pipes, when the machine is broken and replaced, they still work perfectly fine, and they do not need to be broken and placed again to work properly.

**Comment by tom5454** [comment]
Can you post a screenshot of the setup?
Does this issue happen if you replace the result pipe with a Crafting Pipe?

**Comment by desagas** [comment]
In this setup, everything is labeled and works until I break the mixer and replace it. Even if I go in and unselect the result, and set it again, it wont work. The only way to have it work again is to replace the results pipe.

Here is the setup: https://imgur.com/81MRG12

**Comment by desagas** [comment]
Okay, replacing the results pipe with the crafting pipe **does** work, even after breaking and replacing the machine.

I tried the same thing with a chassis mk5, and it sadly does the same thing as the results pipe, after the machine is broken and replaced, it won't retrieve crafted items without breaking and replacing it.

**Comment by tom5454** [comment]
I can't reproduce this, but I added an update detection and it 'should' fix this issue, please test the latest version.

**Comment by desagas** [comment]
I will do. Thank you!
