### ISSUE TITLE
[Request] Stack Extraction from Result Pipe

### ISSUE THREAD

**Issue by desagas** [tom5454/LogisticsBridge#38]
I would like to request if possible the ItemStack extraction upgrade being able to be applied to the result pipe or internally in the crafting manager where it works. Currently, I can attach it to the crafting module in the crafting manager, but, it does absolutely nothing when applied in there.

**Comment by hqpwca** [comment]
Same request. Just found that when craft large batch of items, result items will stuck in the block and been pulled out every several seconds, making the whole processing chain stuck.

**Comment by ArmaWizard** [comment]
It says "sends 16 items into the network" but it only pulls one item per second in my case.

**Comment by tom5454** [comment]
I added an Advanced Extraction Upgrade that can be installed in the Result Pipe and Bridge Pipe.

**Comment by desagas** [comment]
Works perfectly. Much faster, thank you!
