### ISSUE TITLE
Logistics Bridge Pipe

### ISSUE THREAD

**Issue by Enterprise12nx01** [tom5454/LogisticsBridge#44]
The bridge pipe only allows one item to be pulled at a time with the RS bridge block, it was pulling more before last update. no upgrades can be applied to it

**Comment by tom5454** [comment]
Try installing an Advanced Extraction Upgrade into the bridge pipe.

**Comment by Enterprise12nx01** [comment]
Will try again, but it didn't seem to let me insert any upgrades or modules

**Comment by Enterprise12nx01** [comment]
confirmed, i cannot place upgrades or module upgrades in it, even when trying to use the pipe controller

**Comment by Enterprise12nx01** [comment]
Any update on this?

**Comment by Enterprise12nx01** [comment]
Can i get any help or fix with this?? i have tried everything to extract more than 1 item, if i request a stack, it takes 1 item at a time!
no modules or upgrades can be inserted into the bridge pipe

**Comment by tom5454** [comment]
I just tested it and it you can insert Advanced Extraction Upgrades by either right clicking then on the Bridge Pipe or using the Pipe Controller. You have to make the Advanced Extraction Upgrade.

**Comment by Enterprise12nx01** [comment]
ok i was confusing it with the other upgrades, what is the max of those you can put in?

**Comment by tom5454** [comment]
8 is the max.
