### ISSUE TITLE
Bridge would randomly just pause and stop crafting.

### ISSUE THREAD

**Issue by SigmaSnake** [tom5454/LogisticsBridge#5]
![2019-09-04_11 46 14](https://user-images.githubusercontent.com/54494265/64274937-1296b500-cf0a-11e9-93f5-5d79815226d6.png)
![2019-09-04_11 46 29](https://user-images.githubusercontent.com/54494265/64274942-14f90f00-cf0a-11e9-9ae7-67990bb13b0b.png)
![2019-09-04_11 49 10](https://user-images.githubusercontent.com/54494265/64274976-29d5a280-cf0a-11e9-9596-df097dc13a45.png)

As you can see, I am trying to craft an awakened draconium block. First it needs to craft 6 wyvern cores. It crafted the first 5 and then just stopped and decided it did not want to craft anymore. Reloading the world does not help. Breaking and replacing the bridges seems to let some of the items through, but not all of them.

**Comment by tom5454** [comment]
Please test it with v1.2.1
I think I fixed it,

**Comment by SigmaSnake** [comment]
Ok, so I told AE to craft me 4 Awakened Draconium. It interpreted those instructions as 4 sets of 4 awakened draconium. It then proceeded to craft one set and stopped. 
![2019-09-16_16 06 07](https://user-images.githubusercontent.com/54494265/64993607-1e845e80-d89c-11e9-87e9-1f0adce91fb0.png)

**Comment by tom5454** [comment]
Please test it with v1.2.2
I think I fixed it,

**Comment by SigmaSnake** [comment]
It does appear the issue with it randomly pausing and stopping has been resolved. That being said, I am still concerned about the fact it ignores the fact the recipe outputs 4 awakened draconium rather than just 1. Is that not able to be fixed or?

**Comment by tom5454** [comment]
If bridge pipe is set as default route it will recognise multipile outputs.
