### ISSUE TITLE
Weird issue about multiple items in 1 package

### ISSUE THREAD

**Issue by KorewaLidesu** [tom5454/LogisticsBridge#62]
Version: 1.3.14 (Minecraft 1.12.2)

Issue: I'm on the way to make the recipe:
- It require me to set package with 4 glowstone.
- And when I try to craft it, the recipe wasn't work as intended. 
> ++ Check the crafting monitor, it showing that 4 glowstones was used but the package that contain those glowstones wasn't craft-ed. 
> ++ And when I check in my network, there is a package that contain glowstone but when I r-click it, find out it just has 1 glowstone in the package.
- I have trying put 4 package in the recipe but seem like it only count one package for what ever reason (?)
Can you check out why it wasn't work? And maybe a quick fix to it?

**Comment by madokaorimura** [comment]
Sorry for no pics since my 🥔 computer and the mod get me away from screenshot stuff

**Comment by KorewaLidesu** [comment]
![Pic1](https://i.imgur.com/EbUeDD1.png)
![Pic2](https://i.imgur.com/HRPYhmj.png)
![Pic3](https://i.imgur.com/AkIceo8.png)

**Comment by BLucky-gh** [comment]
Hi, any updates on this issue from any of the devs?

**Comment by KorewaLidesu** [comment]
> Hi, any updates on this issue from any of the devs?

Still, no

**Comment by Domaman202** [comment]
See https://www.curseforge.com/minecraft/mc-mods/logistics-bridge-dmnedition

**Comment by KorewaLidesu** [comment]
Fixed in https://github.com/KorewaLidesu/TestBridge/pull/11
