### ISSUE TITLE
Crash when trying to start

### ISSUE THREAD

**Issue by flyingperson23** [tom5454/LogisticsBridge#8]
I crash when trying to start with all the latest versions of the mods, crash report here https://pastebin.com/NkiRSNGF

**Comment by geobr1990** [comment]
I'm getting this exact same crash on my server after updating to 1.2.3.

**Comment by geobr1990** [comment]
After updating Logistics Bridge from 1.2.2 to 1.2.3, I am getting an identical crash to the one reported above (on both my server and client). Rolling back to 1.2.2 is the only way I can start the game. Details:

Minecraft 1.12.2
Star Tech 2.3.1 modpack (manually updating LB causes the crash).
Forge 2847
Logistics Bridge 1.2.3 and Logistics Pipes 0.10.2.211
